
all: pfb pfbt

pfb:
	gcc -o pointer_finger_bitmask pointer_finger_bitmask.c

pfbt:
	gcc -o pointer_finger_touch_bitmask pointer_finger_touch_bitmask.c

clean:
	rm -rf pointer_finger_bitmask pointer_finger_touch_bitmask
